name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

env:
  VERSION: 0.2.8

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Download bin
        run: |
          url="https://github.com/MarcelCoding/zia/releases/download/v$VERSION/zia-server_x86_64-unknown-linux-gnu_static"
          wget -O ./deb/opt/vyatta-zia-server/zia-server ${url}

      - name: Adjust version number for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i "s|Version:.*|Version: ${GITHUB_REF#refs/*v}|" ./deb/DEBIAN/control

      - name: Build deb
        run: |
          chmod +x deb/DEBIAN/postinst
          dpkg-deb --build --root-owner-group deb

      - name: Rename deb
        run: mv deb.deb vyatta-zia-server_$(dpkg-deb -f deb.deb Version)_$(dpkg-deb -f deb.deb Architecture).deb

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: debian-vyatta-zia-server
          path: "vyatta-zia-server_*.deb"

      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["vyatta-zia-server_*.deb"]'
